In [1]:
# ===================================================================
# PASO 1: CONFIGURACI√ìN E INSTALACI√ìN DE LIBRER√çAS
# ===================================================================

import pandas as pd
import requests
import sqlite3

print("‚úÖ Librer√≠as importadas.")

# ===================================================================
# PASO 2: EXTRACCI√ìN (EXTRACT) DE LOS DATOS
# ===================================================================

# La plataforma datos.gov.co usa la API de Socrata. Podemos usarla para
# descargar los datos directamente, lo que es m√°s eficiente que bajar un CSV.
# Aumentamos el l√≠mite para traer m√°s filas (ajusta si es necesario).
api_url = "https://www.datos.gov.co/resource/nudc-7mev.json?$limit=50000"

print(f"üì• Extrayendo datos desde: {api_url}")

try:
    response = requests.get(api_url)
    response.raise_for_status()  # Lanza un error si la petici√≥n falla (ej: 404)
    data = response.json()
    df_raw = pd.DataFrame(data)
    print(f"‚úÖ ¬°Extracci√≥n exitosa! Se cargaron {len(df_raw)} filas.")
    display(df_raw.head())

except requests.exceptions.RequestException as e:
    print(f"‚ùå Error al extraer los datos: {e}")
    df_raw = pd.DataFrame() # Creamos un dataframe vac√≠o para evitar errores posteriores

except Exception as e:
    print(f"‚ùå Ocurri√≥ un error inesperado: {e}")
    df_raw = pd.DataFrame()

‚úÖ Librer√≠as importadas.
üì• Extrayendo datos desde: https://www.datos.gov.co/resource/nudc-7mev.json?$limit=50000
‚úÖ ¬°Extracci√≥n exitosa! Se cargaron 14585 filas.

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,2023,05004,Abriaqu√≠,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,...,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,...,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,...,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
3,2023,97001,Mit√∫,97,Vaup√©s,3831,Vaup√©s (ETC),10986,59.57,59.57,...,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
4,2023,97161,Caruru,97,Vaup√©s,3831,Vaup√©s (ETC),1228,51.3,51.3,...,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN

## aprendiendo pandas

Queremos obtener una informacion

In [2]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14585 entries, 0 to 14584
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   a_o                          14585 non-null  object
 1   c_digo_municipio             14585 non-null  object
 2   municipio                    14585 non-null  object
 3   c_digo_departamento          14585 non-null  object
 4   departamento                 14585 non-null  object
 5   c_digo_etc                   14585 non-null  object
 6   etc                          14585 non-null  object
 7   poblaci_n_5_16               14579 non-null  object
 8   tasa_matriculaci_n_5_16      14470 non-null  object
 9   cobertura_neta               14474 non-null  object
 10  cobertura_neta_transici_n    14533 non-null  object
 11  cobertura_neta_primaria      14494 non-null  object
 12  cobertura_neta_secundaria    14491 non-null  object
 13  cobertura_neta_media         14492 non-null  object
 14  cobertura_bruta              14517 non-null  object
 15  cobertura_bruta_transici_n   14488 non-null  object
 16  cobertura_bruta_primaria     14504 non-null  object
 17  cobertura_bruta_secundaria   14497 non-null  object
 18  cobertura_bruta_media        14458 non-null  object
 19  deserci_n                    14443 non-null  object
 20  deserci_n_transici_n         13682 non-null  object
 21  deserci_n_primaria           14343 non-null  object
 22  deserci_n_secundaria         14315 non-null  object
 23  deserci_n_media              13851 non-null  object
 24  aprobaci_n                   14560 non-null  object
 25  aprobaci_n_transici_n        14492 non-null  object
 26  aprobaci_n_primaria          14560 non-null  object
 27  aprobaci_n_secundaria        14531 non-null  object
 28  aprobaci_n_media             14484 non-null  object
 29  reprobaci_n                  14499 non-null  object
 30  reprobaci_n_transici_n       14492 non-null  object
 31  reprobaci_n_primaria         14488 non-null  object
 32  reprobaci_n_secundaria       14479 non-null  object
 33  reprobaci_n_media            14440 non-null  object
 34  repitencia                   14442 non-null  object
 35  repitencia_transici_n        14426 non-null  object
 36  repitencia_primaria          14437 non-null  object
 37  repitencia_secundaria        14433 non-null  object
 38  repitencia_media             14446 non-null  object
 39  tama_o_promedio_de_grupo     7572 non-null   object
 40  sedes_conectadas_a_internet  7768 non-null   object
dtypes: object(41)
memory usage: 4.6+ MB

Generemos una "muestra" del conjunto de datos
1. Tomando los primeros registros  del conjunto de datos

In [ ]:
pd.set_option('display.max_columns', None)## muestra todos los datos

In [3]:
df_raw.head(15)

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,2023,05004,Abriaqu√≠,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,...,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,...,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,...,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
3,2023,97001,Mit√∫,97,Vaup√©s,3831,Vaup√©s (ETC),10986,59.57,59.57,...,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
4,2023,97161,Caruru,97,Vaup√©s,3831,Vaup√©s (ETC),1228,51.3,51.3,...,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN
5,2023,97511,Pacoa,97,Vaup√©s,3831,Vaup√©s (ETC),1678,54.29,54.29,...,0,0,0,23.21,25.86,30.3,14.25,6.59,NaN,NaN
6,2023,97666,Taraira,97,Vaup√©s,3831,Vaup√©s (ETC),814,22.6,22.6,...,0,0,0,21.58,13.33,22.29,0,0,NaN,NaN
7,2023,97777,Papunaua,97,Vaup√©s,3831,Vaup√©s (ETC),209,0,0,...,0,0,0,0,0,0,0,0,NaN,NaN
8,2023,97889,Yavarat√©,97,Vaup√©s,3831,Vaup√©s (ETC),561,47.95,47.95,...,0,0,0,12.33,3.13,19.5,3.95,4,NaN,NaN
9,2023,99001,Puerto Carre√±o,99,Vichada,3832,Vichada (ETC),4641,144.52,144.52,...,12.96,18.84,8.81,11.18,0.82,13.25,10.45,6.39,NaN,NaN
10,2023,99524,La Primavera,99,Vichada,3832,Vichada (ETC),2659,95.94,95.94,...,13.46,8.91,4.8,13.98,1.55,19.37,11.8,1.48,NaN,NaN
11,2023,99624,Santa Rosal√≠a,99,Vichada,3832,Vichada (ETC),1159,83.87,83.87,...,7.69,17.89,2.83,13.99,0,16.48,17.01,2.83,NaN,NaN
12,2023,99773,Cumaribo,99,Vichada,3832,Vichada (ETC),25357,49.85,49.85,...,21.35,9.87,5.13,21.27,0.52,27.83,11.87,6.56,NaN,NaN
13,2023,95001,San Jos√© del Guaviare,95,Guaviare,3830,Guaviare (ETC),13980,90.57,90.54,...,6.84,15.69,5.67,10.84,6.83,11.44,13.61,1.92,NaN,NaN
14,2023,94887,Pana Pana,94,Guain√≠a,3829,Guain√≠a (ETC),718,37.33,37.33,...,6.57,18.75,0,31.37,0,42.93,18.75,6.67,NaN,NaN

2. ahora usamos los indicies para mostrar una fraccion de los datos.

In [ ]:
df_raw.iloc[20:30] #pensemos en estos indices como un intervalo semi abierto

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
20,2023,94001,In√≠rida,94,Guain√≠a,3829,Guain√≠a (ETC),9673,77.42,77.33,...,13.35,15.6,7.33,16.19,8.47,18.36,17.25,6.11,NaN,NaN
21,2023,91798,Tarapac√°,91,Amazonas,3828,Amazonas (ETC),1327,50.04,50.04,...,1.26,24.2,63.16,26.09,1.28,28.87,29.3,31.58,NaN,NaN
22,2023,91669,Puerto Santander,91,Amazonas,3828,Amazonas (ETC),618,63.75,63.75,...,3.09,7.87,0,16.67,1.85,19.69,16.85,16.67,NaN,NaN
23,2023,91540,Puerto Nari√±o,91,Amazonas,3828,Amazonas (ETC),3232,55.07,55.07,...,13.51,15.47,5.32,15.37,5.85,18.61,16.75,3.72,NaN,NaN
24,2023,91536,Puerto Arica,91,Amazonas,3828,Amazonas (ETC),274,83.94,83.94,...,0.67,0,0,11.49,0,12.75,10.45,17.39,NaN,NaN
25,2023,91530,Puerto Alegr√≠a,91,Amazonas,3828,Amazonas (ETC),211,65.4,65.4,...,9.38,6.25,0,18.62,29.41,19.79,9.38,0,NaN,NaN
26,2023,91460,Miriti - Paran√°,91,Amazonas,3828,Amazonas (ETC),571,49.39,49.39,...,0,0,0,12.5,17.65,11.05,18,2.63,NaN,NaN
27,2023,91430,La Victoria,91,Amazonas,3828,Amazonas (ETC),169,14.2,14.2,...,0,0,0,16.67,20,15.79,0,0,NaN,NaN
28,2023,91407,La Pedrera,91,Amazonas,3828,Amazonas (ETC),1203,67.17,67.17,...,0.6,5.73,4.62,12.97,2.63,20.24,4.85,3.08,NaN,NaN
29,2023,91405,La Chorrera,91,Amazonas,3828,Amazonas (ETC),1197,50.04,50.04,...,11.62,8.64,14,26.42,5.56,24.77,37.27,12,NaN,NaN

In [7]:
df_raw.sample(frac=0.01, random_state=123456)

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
10516,2014,50330,Mesetas,50,Meta,3796,Meta (ETC),2904,76.41,89.01,...,0,0,0,0,0,0,0,0,25.59,1.75
2152,2022,5628,Sabanalarga,5,Antioquia,3758,Antioquia (ETC),2046,79.33,79.33,...,0.73,0.87,0,8.32,0,12.39,6.09,1.38,NaN,NaN
9454,2015,41660,Saladoblanco,41,Huila,3790,Huila (ETC),3108,86.87,86.87,...,5.56,0.47,0.45,2.68,1.95,3.96,1.29,0.45,33.45,12.5
10130,2014,97889,Yavarat√©,97,Vaup√©s,3831,Vaup√©s (ETC),386,75.39,87.65,...,0,0,0,3.61,0,4.9,2.53,0,9.76,16.67
11152,2014,5411,Liborina,5,Antioquia,3758,Antioquia (ETC),1985,105.29,89.66,...,0,0,0,2.87,2.56,2.34,3.62,3.52,27.09,73.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4912,2019,50251,El Castillo,50,Meta,3796,Meta (ETC),1766,95.13,95.13,...,4.17,3.89,1.6,1.44,0,1.19,2.54,0,NaN,NaN
11711,2013,41503,Oporapa,41,Huila,3790,Huila (ETC),3997,68.83,68.8,...,4.47,9.14,8.14,1.26,0,2.09,0.58,0,NaN,11.11
9773,2015,15897,Zetaquira,15,Boyac√°,3769,Boyac√° (ETC),981,97.96,97.96,...,0,4.52,3.64,0.79,0,1.48,0.53,0,27.27,0
3428,2020,81065,Arauquita,81,Arauca,3824,Arauca (ETC),13580,68.03,68.03,...,7.96,15.51,7.36,6.42,1.93,5.15,10.88,2.03,NaN,NaN
8460,2016,41006,Acevedo,41,Huila,3790,Huila (ETC),9107,81,81.04,...,5.31,11.24,7.26,3.42,0.69,4.48,2.44,2.35,27.244,14.29

In [9]:
df_raw.sample(n= 10, random_state=123456)

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
10516,2014,50330,Mesetas,50,Meta,3796,Meta (ETC),2904,76.41,89.01,...,0,0,0,0,0,0,0,0,25.59,1.75
2152,2022,5628,Sabanalarga,5,Antioquia,3758,Antioquia (ETC),2046,79.33,79.33,...,0.73,0.87,0,8.32,0,12.39,6.09,1.38,NaN,NaN
9454,2015,41660,Saladoblanco,41,Huila,3790,Huila (ETC),3108,86.87,86.87,...,5.56,0.47,0.45,2.68,1.95,3.96,1.29,0.45,33.45,12.5
10130,2014,97889,Yavarat√©,97,Vaup√©s,3831,Vaup√©s (ETC),386,75.39,87.65,...,0,0,0,3.61,0,4.9,2.53,0,9.76,16.67
11152,2014,5411,Liborina,5,Antioquia,3758,Antioquia (ETC),1985,105.29,89.66,...,0,0,0,2.87,2.56,2.34,3.62,3.52,27.09,73.53
2210,2022,5134,Campamento,5,Antioquia,3758,Antioquia (ETC),2223,72.15,72.15,...,10.41,6.99,1.06,9.12,0,13.49,6.99,0.53,NaN,NaN
6968,2017,68368,Jes√∫s Mar√≠a,68,Santander,3808,Santander (ETC),657,87.2,87.21,...,4.76,9.42,3.48,0,0,0,0,0,25.333,8.33
8852,2016,73675,San Antonio,73,Tolima,3815,Tolima (ETC),3510,90.9,90.85,...,6.59,8.57,5.08,0.18,0,0.12,0.18,0.68,24.985,56.67
13385,2012,5475,Murind√≥,5,Antioquia,3758,Antioquia (ETC),1023,95.6,95.6,...,0,0,0,0,0,0,0,0,30.33,5
2067,2022,13458,Montecristo,13,Bol√≠var,3767,Bol√≠var (ETC),4308,75.35,75.35,...,10.87,12.12,1.79,13.41,3.79,16.19,13.2,3.57,NaN,NaN

In [6]:
df_raw.iloc[20:30,1:6]

,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc
20,94001,In√≠rida,94,Guain√≠a,3829
21,91798,Tarapac√°,91,Amazonas,3828
22,91669,Puerto Santander,91,Amazonas,3828
23,91540,Puerto Nari√±o,91,Amazonas,3828
24,91536,Puerto Arica,91,Amazonas,3828
25,91530,Puerto Alegr√≠a,91,Amazonas,3828
26,91460,Miriti - Paran√°,91,Amazonas,3828
27,91430,La Victoria,91,Amazonas,3828
28,91407,La Pedrera,91,Amazonas,3828
29,91405,La Chorrera,91,Amazonas,3828

In [5]:
df_raw.loc[20:30] #pensemos en estos indices como un intervalo cerrado

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
20,2023,94001,In√≠rida,94,Guain√≠a,3829,Guain√≠a (ETC),9673,77.42,77.33,...,13.35,15.6,7.33,16.19,8.47,18.36,17.25,6.11,NaN,NaN
21,2023,91798,Tarapac√°,91,Amazonas,3828,Amazonas (ETC),1327,50.04,50.04,...,1.26,24.2,63.16,26.09,1.28,28.87,29.3,31.58,NaN,NaN
22,2023,91669,Puerto Santander,91,Amazonas,3828,Amazonas (ETC),618,63.75,63.75,...,3.09,7.87,0,16.67,1.85,19.69,16.85,16.67,NaN,NaN
23,2023,91540,Puerto Nari√±o,91,Amazonas,3828,Amazonas (ETC),3232,55.07,55.07,...,13.51,15.47,5.32,15.37,5.85,18.61,16.75,3.72,NaN,NaN
24,2023,91536,Puerto Arica,91,Amazonas,3828,Amazonas (ETC),274,83.94,83.94,...,0.67,0,0,11.49,0,12.75,10.45,17.39,NaN,NaN
25,2023,91530,Puerto Alegr√≠a,91,Amazonas,3828,Amazonas (ETC),211,65.4,65.4,...,9.38,6.25,0,18.62,29.41,19.79,9.38,0,NaN,NaN
26,2023,91460,Miriti - Paran√°,91,Amazonas,3828,Amazonas (ETC),571,49.39,49.39,...,0,0,0,12.5,17.65,11.05,18,2.63,NaN,NaN
27,2023,91430,La Victoria,91,Amazonas,3828,Amazonas (ETC),169,14.2,14.2,...,0,0,0,16.67,20,15.79,0,0,NaN,NaN
28,2023,91407,La Pedrera,91,Amazonas,3828,Amazonas (ETC),1203,67.17,67.17,...,0.6,5.73,4.62,12.97,2.63,20.24,4.85,3.08,NaN,NaN
29,2023,91405,La Chorrera,91,Amazonas,3828,Amazonas (ETC),1197,50.04,50.04,...,11.62,8.64,14,26.42,5.56,24.77,37.27,12,NaN,NaN
30,2023,91263,El Encanto,91,Amazonas,3828,Amazonas (ETC),656,49.09,49.09,...,1.02,5,0,9.62,0,9.18,14,3.45,NaN,NaN

In [12]:
df_raw.tail(10)

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
14575,2011,5045,Apartad√≥,5,Antioquia,7692,Apartado,45592,66.51,66.5,...,0.47,1.98,2.07,1.86,0.06,1.81,2.67,0.95,26.21,65.91
14576,2011,5044,Anza,5,Antioquia,3758,Antioquia (ETC),1873,86.07,86.1,...,NaN,5.69,3.7,0,0,0,0,0,16.3,88.89
14577,2011,5042,Santaf√© de Antioquia,5,Antioquia,3758,Antioquia (ETC),5963,84.59,84.6,...,6.14,5.47,4.13,3.25,0,2.36,6.09,1.94,23.04,90.91
14578,2011,5040,Anor√≠,5,Antioquia,3758,Antioquia (ETC),3983,92.09,92.1,...,2.14,1,0.42,0.48,0,0.69,0,0,20.09,63.93
14579,2011,5038,Angostura,5,Antioquia,3758,Antioquia (ETC),3344,81.7,81.7,...,3.73,1.93,2.27,3.92,0,5.16,1.92,2.96,20.29,86.49
14580,2011,5036,Angel√≥polis,5,Antioquia,3758,Antioquia (ETC),1707,78.85,78.9,...,3.61,9.5,7.32,0.71,0,0.7,1.08,0,19.57,100
14581,2011,5034,Andes,5,Antioquia,3758,Antioquia (ETC),10244,84.45,84.5,...,0.58,0.04,2.69,5.41,0.73,5.53,6.9,4.11,24.43,93.44
14582,2011,5031,Amalfi,5,Antioquia,3758,Antioquia (ETC),5552,97.71,97.7,...,0,0,0,NaN,0.83,NaN,9.93,4.47,20.01,53.45
14583,2011,5030,Amag√°,5,Antioquia,3758,Antioquia (ETC),6631,78.65,78.7,...,6.73,14.46,7.45,0.42,0,0.24,0.91,0,25.05,83.33
14584,2011,5021,Alejandr√≠a,5,Antioquia,3758,Antioquia (ETC),702,118.52,118.5,...,2.16,4.39,8.04,0.6,0,0.96,0,0,32.14,81.25

vamos a crear una copia de la base de datos

In [16]:
df_raw2 = df_raw.copy()

In [17]:
df_raw.shape # lo mismo que el dim de r

(14585, 41)

In [18]:
df_raw2['new_index'] = range(1,df_raw.shape[0]+1)

In [ ]:
df_raw2.head()